import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { Octokit } from "@octokit/rest";
import type { DraftedArticle, Trigger } from "./types";
import { markDrafted } from "./backlog";

const RESOURCES_DIR = path.join(process.cwd(), "content", "resources");

export function writeLocal(article: DraftedArticle): string {
  if (!fs.existsSync(RESOURCES_DIR)) {
    fs.mkdirSync(RESOURCES_DIR, { recursive: true });
  }
  const filePath = path.join(RESOURCES_DIR, `${article.slug}.md`);
  fs.writeFileSync(filePath, article.rawMarkdown + "\n");
  return filePath;
}

/**
 * Build the branch name. Includes ISO week so multiple runs in the same
 * week don't collide, and slug so it's self-describing.
 */
export function branchName(article: DraftedArticle, trigger: Trigger): string {
  const d = new Date();
  const year = d.getUTCFullYear();
  const week = isoWeek(d).toString().padStart(2, "0");
  const triggerPrefix = trigger === "vercel-cron" ? "cron" : trigger === "github-actions" ? "gh" : trigger;
  return `auto/${triggerPrefix}-resource-${article.slug}-${year}w${week}`;
}

function isoWeek(d: Date): number {
  const target = new Date(d.valueOf());
  const dayNr = (d.getUTCDay() + 6) % 7;
  target.setUTCDate(target.getUTCDate() - dayNr + 3);
  const firstThursday = new Date(target.getUTCFullYear(), 0, 4);
  return (
    1 +
    Math.round(
      ((target.getTime() - firstThursday.getTime()) / 86400000 -
        3 +
        ((firstThursday.getUTCDay() + 6) % 7)) /
        7
    )
  );
}

type PrOptions = {
  owner: string;
  repo: string;
  token: string;
  baseBranch: string;
  trigger: Trigger;
};

/**
 * Create a branch, commit the article and backlog update, push, open a PR.
 * Uses local git (via execSync) for the commit, Octokit for the PR creation —
 * this keeps the commit path identical to what a human would produce.
 */
export async function openPullRequest(
  article: DraftedArticle,
  opts: PrOptions
): Promise<string> {
  const branch = branchName(article, opts.trigger);
  const filePath = writeLocal(article);
  markDrafted(article.slug);

  // git ops — localized try/catch so a branch-already-exists error surfaces cleanly.
  git(`git fetch origin ${opts.baseBranch}`);
  git(`git checkout -B ${branch} origin/${opts.baseBranch}`);
  // Re-write the article on the new branch (checkout discarded the working-tree write above).
  writeLocal(article);
  markDrafted(article.slug);
  git(`git add ${path.relative(process.cwd(), filePath)} content/resources/_backlog.json`);
  git(
    `git -c user.email="bot@renewalengineai.com" -c user.name="RenewalEngineAI Content Bot" ` +
      `commit -m ${shellQuote(commitMessage(article, opts.trigger))}`
  );

  // Use the PAT as the push credential.
  const remoteUrl = `https://x-access-token:${opts.token}@github.com/${opts.owner}/${opts.repo}.git`;
  git(`git push -u ${remoteUrl} ${branch}`);

  const octokit = new Octokit({ auth: opts.token });
  const pr = await octokit.pulls.create({
    owner: opts.owner,
    repo: opts.repo,
    head: branch,
    base: opts.baseBranch,
    title: `Auto-draft: ${article.title}`,
    body: prBody(article, opts.trigger),
  });

  // Re-record the PR URL on the backlog entry.
  markDrafted(article.slug, pr.data.html_url);

  return pr.data.html_url;
}

function commitMessage(article: DraftedArticle, trigger: Trigger): string {
  return `feat(resources): auto-draft ${article.title}\n\nTrigger: ${trigger}\nSlug: ${article.slug}\nWords: ${article.wordCount}\n`;
}

function prBody(article: DraftedArticle, trigger: Trigger): string {
  const sources = article.sources.length
    ? article.sources.map((s, i) => `${i + 1}. [${s.title}](${s.url})`).join("\n")
    : "(no external sources — drafted from house knowledge)";

  return [
    `Auto-drafted resource article.`,
    ``,
    `- **Trigger**: \`${trigger}\``,
    `- **Slug**: \`${article.slug}\``,
    `- **Category**: ${article.category}`,
    `- **Primary keyword**: \`${article.primaryKeyword}\``,
    `- **Word count**: ${article.wordCount}`,
    `- **Read time**: ${article.readTime} min`,
    ``,
    `## Review checklist`,
    `- [ ] Tone matches house voice (compare against existing /resources)`,
    `- [ ] Claims are accurate and match our verified outcomes`,
    `- [ ] Internal links resolve`,
    `- [ ] No fabricated product features or pricing`,
    `- [ ] No em-dashes / banned cliches`,
    `- [ ] Table/list/comparison present`,
    `- [ ] CTA sits naturally in the closing`,
    ``,
    `## Sources`,
    sources,
    ``,
    `---`,
    `Generated by the weekly content engine. Merge after review — do not auto-merge.`,
  ].join("\n");
}

function git(cmd: string): string {
  return execSync(cmd, { stdio: ["ignore", "pipe", "pipe"] }).toString();
}

function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * Pure-Octokit path for serverless environments (Vercel) where there's
 * no git binary or writable repo checkout. Creates the branch + commits
 * via the GitHub Contents API, then opens a PR.
 *
 * Trade-off vs openPullRequest: this path does NOT update the local
 * backlog file (no writable FS). The backlog entry is updated on the
 * remote branch as part of the commit, so the next run against the
 * main branch still sees the updated backlog.
 */
export async function openPullRequestViaAPI(
  article: DraftedArticle,
  opts: PrOptions,
  updatedBacklog: string
): Promise<string> {
  const octokit = new Octokit({ auth: opts.token });
  const branch = branchName(article, opts.trigger);

  // Resolve base SHA
  const { data: baseRef } = await octokit.git.getRef({
    owner: opts.owner,
    repo: opts.repo,
    ref: `heads/${opts.baseBranch}`,
  });
  const baseSha = baseRef.object.sha;

  // Create branch
  try {
    await octokit.git.createRef({
      owner: opts.owner,
      repo: opts.repo,
      ref: `refs/heads/${branch}`,
      sha: baseSha,
    });
  } catch (err) {
    if (
      !(err instanceof Error) ||
      !err.message.toLowerCase().includes("reference already exists")
    ) {
      throw err;
    }
  }

  // Write article file on the branch
  await octokit.repos.createOrUpdateFileContents({
    owner: opts.owner,
    repo: opts.repo,
    path: `content/resources/${article.slug}.md`,
    message: `feat(resources): auto-draft ${article.title}`,
    content: Buffer.from(article.rawMarkdown + "\n").toString("base64"),
    branch,
    committer: {
      name: "RenewalEngineAI Content Bot",
      email: "bot@renewalengineai.com",
    },
    author: {
      name: "RenewalEngineAI Content Bot",
      email: "bot@renewalengineai.com",
    },
  });

  // Update backlog on the branch — needs the current SHA of the file on the branch.
  const { data: existing } = await octokit.repos.getContent({
    owner: opts.owner,
    repo: opts.repo,
    path: "content/resources/_backlog.json",
    ref: branch,
  });
  const existingSha = Array.isArray(existing) ? undefined : existing.sha;

  await octokit.repos.createOrUpdateFileContents({
    owner: opts.owner,
    repo: opts.repo,
    path: "content/resources/_backlog.json",
    message: `chore(resources): mark ${article.slug} drafted`,
    content: Buffer.from(updatedBacklog).toString("base64"),
    branch,
    sha: existingSha,
    committer: {
      name: "RenewalEngineAI Content Bot",
      email: "bot@renewalengineai.com",
    },
    author: {
      name: "RenewalEngineAI Content Bot",
      email: "bot@renewalengineai.com",
    },
  });

  const pr = await octokit.pulls.create({
    owner: opts.owner,
    repo: opts.repo,
    head: branch,
    base: opts.baseBranch,
    title: `Auto-draft: ${article.title}`,
    body: prBody(article, opts.trigger),
  });

  return pr.data.html_url;
}
